---
title: "2015896 - GEOMATICA BASICA"
subtitle: "Academic Year: 2023"
format: html
---

::: {.callout-important collapse=false}

## DESCRIPCIÓN DE LA ASIGNATURA:

### OBJETIVOS:
- Entender y aplicar conceptos, métodos y técnicas geoespaciales.
- Desarrollar destrezas prácticas para realizar procesos digitales útiles en las ciencias agronómicas.
- Brindar oportunidades para desarrollar pensamiento crítico, razonamiento espacial y calidad argumentativa.

### COMPETENCIAS GENÉRICAS: 
- Capacidad para usar las herramientas tecnológicas, de la información y de la comunicación
- Capacidad para organización y planificación
- Capacidad de comunicación

### COMPETENCIAS ESPECÍFICAS:
- Capacidad de abstracción, análisis y síntesis.
- Capacidad de integrar y aplicar los conocimientos en la práctica.
- Capacidad de lectura en inglés.
- Capacidad para organizar y planificar el tiempo.
- Capacidad para desarrollar pensamiento crítico, razonamiento espacial y calidad argumentativa

### METODOLOGIA:
-	Lectura antes de la clase a cargo del estudiante
-   Presentación de conceptos, métodos y técnicas a cargo del profesor
-	Realización de ejercicios prácticos y elaboración de reportes técnicos a cargo  del estudiante
:::


## CONTENIDO DETALLADO 

::: {.callout-important collapse=true}

Semana 1 –  Introducción, contexto y conceptos básicos

Semana 2 –  Datos geoespaciales e información geográfica

Semana 3 -  Sistemas de coordenadas y proyecciones cartográticas

Semana 4 - Conceptos básicos de cartografía

Semana 5 - Modelos digitales de elevación

Semana 6 –  Sistemas de información geográfica

Semana 7 –  Servicios web geográficos

Semana 8 –  Sistemas satelitales de navegación global

Semana 9 – Calidad de datos geográficos

Semana 10 – Principios físicos de percepción remota

Semana 11 – Percepción remota de la vegetación

Semana 12 - Métodos determinísticos de interpolación espacial

Semanas 14 y 15 - Métodos geoestadísticos de interpolación espacial

Semana 16 - Agricultura digital
:::


## EVALUACIÓN DEL CURSO: 

::: {.callout-important collapse=false}

-	Presentación de dos exámenes escritos sobre aspectos teóricos (50%)
    - Examen 1 - 20 de Septiembre
    - Examen 2 - 22 de Noviembre
-	Entrega de dos informes técnicos  (50%)
    - Informe 1 - 27 de Septiembre
    - Informe 2 - 29 de Noviembre

:::

## BIBLIOGRAFIA

::: {.callout-important collapse=true}

Brunsdon, C. and Comber, L. An introduction to R for spatial analysis and mapping [2nd ed.], SAGE, 2019.

Duncombe, R. Digital technologies for Agricultural and Rural Development in the Global South. CABI, 2018.

Gomarasca, M. Basics of Geomatics. Springer, 2009.

Longley, P.A., Goodchild M.F., Maguire, D.J. and Rhind, D.W. Geographic Information Systems [4th edition], Wiley, 2015.

Lovelace, R., Nowosad, J., and Muenchow, J. Geocomputation with R [2nd ed.],CRC Press, 2023. Available at https://geocompr.robinlovelace.net/

Pebesma, E. & Bivand, R. Spatial data science with applications in R. CRC Press, 2023.

Plant, R.E. Spatial Data Analysis in Ecology and Agriculture Using R [2nd ed.], CRC Press, 2019.

Wegman, M., Leutner, B., and Dech, S. Remote Sensing and GIS for Ecologists: using Open Source Software, Pelagic Publishing, 2016.

:::
